### ISSUE TITLE
Hide Kick global emotes from the emote picker and tab-completion if there's a corresponding 7TV emote for it

### ISSUE THREAD

**Issue by RevSnowfox** [Xzensi/NipahTV#111]
For example hide the Kick global emote KatKiss if the channel has the 7TV emote catKiss, which is the default name for the kissing cat emote.

Obviously this means going over each Kick global emote individually and determining what default 7TV emotes names to account for to hide them, so it won't help if the same emotes have wildly different custom names, but it would still reduce clutter for most channels.

Optionally how about rendering the (inferior) Kick global emotes using their (superior) 7TV counterparts? The emotes being sent would be unchanged, but they would be rendered using a different, better image in chat. plonk

**Comment by Xzensi** [comment]
Implementing emote aliases isn't that simple and we're more or less really only talking about 1 emote here, CatKiss/KatKiss. I feel like it's not worth the effort it takes to implement this just to deduplicate 1 global emote. Also in general, unless there's a good reason, hardcoding emotes is undesirable.
