### ISSUE TITLE
Add support for Zero-width 7TV emotes

### ISSUE THREAD

**Issue by bhdrozgn** [Xzensi/NipahTV#132]
7TV has zero-width emotes, such as:

- https://7tv.app/emotes/6116a00a47935f36575c7bbb
- https://7tv.app/emotes/61298a4aa4d049e179751dbc
- https://7tv.app/emotes/6216d2f73808dfe5c465bc4a
- https://7tv.app/emotes/65db9e7b63263afe0a23ad7c
- https://7tv.app/emotes/6360b863593eb316d898eb78

These emotes have 0 width, meaning they are drawn on top of the prior emote. (e.g., KEKW Fire)
It is also possible to stack multiple zero-width emotes on top of the same emote. (e.g., KEKW ALERT Fire)
The zero-width emotes are drawn like normal emotes in NipahTV.

**Comment by Xzensi** [comment]
Hadn't made issue for this yet so thank you for creating issue for it. Currently prioritizing to implement 7TV username colors before handling this.

#75

**Comment by Xzensi** [comment]
Added in 40a0edb24175f4a20c881ca02556276f4d70cd92
