### ISSUE TITLE
Firefox add-on updates automatically triggers reload of everything resulting in double message rendering when sending messages

### ISSUE THREAD

**Issue by Xzensi** [Xzensi/NipahTV#153]

**Comment by sc0ty** [comment]
Update could be delayed programmatically https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onUpdateAvailable

**Comment by sc0ty** [comment]
Logs are only from reload, don't have them from the start

**Comment by Xzensi** [comment]
Fixed in 2c4aef45f57ad2cf1b3235c9b7e770cf5f84d964
