### ISSUE TITLE
In translucent overlay mode, buttons on the timer component aren't properly translucent on hover

### ISSUE THREAD

**Issue by RevSnowfox** [Xzensi/NipahTV#180]

**Comment by Xzensi** [comment]
Can confirm they are correctly translucent.

![image](https://github.com/user-attachments/assets/73efe610-7639-44e6-9e97-98585a82225c)

If they weren't I think I know what happened which is a bit of a weird edgecase I haven't found out how to reproduce yet. I'll get around to fixing that when I find out how to reproduce it where the entire chat footer (input and all buttons) suddenly becomes either fully transparent or opaque.

Are you able to reproduce this issue?

**Comment by RevSnowfox** [comment]
I forgot to add that they aren't translucent *on hover*; the NTV button gets darkened on hover in translucent mode, however the timer's pause/start and delete buttons don't.

(Not part of the timer, but Kick's native settings button, ie. the cogwheel also won't get darkened on hover. It would be nice to also modify Blerp's button if it's installed.)

**Comment by Xzensi** [comment]
Fixed in 3d0316c9fb44616e43fef2af0ac04981df78726c
