### ISSUE TITLE
After entering just an emoji with Windows emoji bar (Win+semicolon), if you don't do a space/enter real text you cant hit Enter to send it.

### ISSUE THREAD

**Issue by pwnflakes** [Xzensi/NipahTV#186]
It must be something to do with how the 'Enter to send' checks if there's something to send, not considering the way that the emoji was inserted or accounting for it as entered text. Kick natively seems to, as the Chat button ungreys even with Nipah installed, but Enter doesn't work to send it still.

**Comment by Xzensi** [comment]
Fixed in 02035c448f91cb122bc73c32ae9bbe8559d3bff9
