### ISSUE TITLE
QoL: Player should handle end of stream gracefully in theater mode

### ISSUE THREAD

**Issue by RevSnowfox** [Xzensi/NipahTV#52]
If the player is in theater mode (probably even if it's in fullscreen mode) and the stream ends, it becomes unresponsive, you have to refresh the site. It makes theater mode a slight annoyance.

**Comment by Xzensi** [comment]
I agree it's annoying but surely they'll fix this eventually, right? There's quite a lot to do, so it'll be low priority.

**Comment by Xzensi** [comment]
No longer relevant on new Kick website
