### ISSUE TITLE
Implement 7TV name colors and supporter badge

### ISSUE THREAD

**Issue by Xzensi** [Xzensi/NipahTV#75]

**Comment by cmd430** [comment]
when you implement this please make sure you also implement 7tv presence reporting otherwise users who have paints/badges wont tell other clients and wont show up for them

https://github.com/SevenTV/Extension/blob/cc924cbf4483a5436732526418d16002a6e7a6d1/src/worker/worker.http.ts#L205C1-L221C3

**Comment by Xzensi** [comment]
Will do, thanks!
